### ISSUE TITLE
Game Crash Upon Death

### ISSUE THREAD

**Issue by Bloo-dev** [suppergerrie2/AutoF5#1]
### Description
AutoF5 causes the game to crash after dying under certain circumstances. The issue does not occur if `doImmediateRespawn` is on, suggesting an issue with the death screen as a reason. The crash also happens when re-joining a server on which the player is currenlty in the death screen, causing a game crash upon join.

### How to Reproduce
1. Install AutoF5 (`1.0.0`), owo-lib (`0.12.3+1.20.3`), and fabric api (`0.96.4+1.20.4`) on Minecraft 1.20.4, modded with fabric loader (`0.15.6 - 1.20.4`)
2. Create a new world, and use `/kill`.
3. The game immediately crashes, the launcher displays ```The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5498.method_31034()" because the return value of "net.minecraft.class_315.method_31044()" is null```

### Further Info
Installed Mods:
- AutoF5 (`1.0.0`)
- owo-lib (`0.12.3+1.20.3`)
- fabric api (`0.96.4+1.20.4`)
Minecraft Version & Fabric Loader
- Minecraft 1.20.4
- fabric loader (`0.15.6 - 1.20.4`)
Datapacks:
- None
Crash Report:
I can send you one in private if needed.

**Comment by suppergerrie2** [comment]
This should be fixed in v1.0.2 on [curseforge](https://www.curseforge.com/minecraft/mc-mods/auto-f5/files/5159262
).

Feel free to re-open if it still happens.

**Comment by Bloo-dev** [comment]
This was fixed in version 1.0.2 of AutoF5, therefore closing as completed.

@suppergerrie2 reminder to add that version to this repo.
